CineCue/config/routes.rb
Rails.application.routes.draw do

  # Define the root path route ("/")
  root to: 'movies#index'

  get 'books', to: 'movies#books'
  post 'book/:id', to: 'movies#book', as: 'book'
  post 'unbook/:id', to: 'movies#unbook', as: 'unbook'

  get 'signup', to: 'registrations#signup'
  post 'signup', to: 'registrations#signup_form'

  get 'login', to: 'registrations#login'
  post 'login', to: 'registrations#login_form'

  get 'pass', to: 'registrations#edit_pass'
  patch 'pass', to: 'registrations#edit_pass_form'

  patch 'lang', to: 'registrations#edit_lang_form'

  get 'logout', to: 'registrations#logout'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'

  # Catch-all route for undefined paths (triggers 404 error)
  match '*path', to: 'errors#not_found', via: :all

  # Health check route
  get 'up' => 'rails/health#show', as: :rails_health_check

end

CineCue/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

CineCue/app/models/user.rb
require 'scrypt'

class User < ApplicationRecord

  validates :email, format: {
    with: /\A[^@\s]+@[^@\s]+\z/,
    message: "must be a valid email format"
  }

  validates :username, format: {
    with: /\A[a-z0-9]+\z/i,
    message: "can only contain letters and numbers"
  }
  validates :username, length: { minimum: 5, maximum: 24 }
  validates :username, uniqueness: true

  validates :lang, inclusion: { in: %w(en ar tr ur hi es fr), message: "%{value} is not a valid option." }

  validate :password_validation

  def password=(new_password)
    @password = new_password
    self.password_digest = SCrypt::Password.create(new_password)
  end

  def password_validation
    if @password.present?
      unless @password =~ /\A(?=.{8,32})[a-z0-9!#@]*\z/i
        errors.add(:password, "must be between 8 and 64 characters and include valid characters")
      end
    end
  end

  def check?(password)
    SCrypt::Password.new(self.password_digest) == password
  end

end

CineCue/app/controllers/application_controller.rb
require 'json'
require 'faraday'

class ApplicationController < ActionController::Base

  before_action :set_current_user, :tolgit

  def set_current_user
    @user = User.find_by(id: session[:user_id])
  end

  def tolgit

    if @user
      cookies[:lang] = @user.lang
    end
    cookies[:lang] ||= "en"

    @translations = JSON.parse(Faraday.get('https://cdn.tolg.ee/93411aa4fca9f5c1c79802feb5355105/'+cookies[:lang]+'.json').body)

  end

end

CineCue/app/controllers/errors_controller.rb
# app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
  end

  def internal_server_error
  end
end

CineCue/app/controllers/movies_controller.rb
require 'faraday'
require 'json'

class MoviesController < ApplicationController\

  @@api_key = "<set tmdb api key here>"

  def index
    if params[:genre]
      genre = params[:genre]
      @movies = fetch_movies_by_genre(genre, 1)
      @movies2 = fetch_movies_by_genre(genre, 2)
    else
      @movies = []
      @movies2 = []
    end
  end

  def book
    if @user
      movie_id = params[:id]
      @user.update!(bookmarks: JSON.generate(JSON.parse(@user.bookmarks || '[]') << movie_id))
      @user.save
    end
    render plain: "Bookmark requested."
  end

  def unbook
    if @user
      movie_id = params[:id]
      @user.update!(bookmarks: JSON.generate(JSON.parse(@user.bookmarks) - [movie_id]))
      @user.save
    end
    redirect_to books_path
  end

  def books
    if @user
      @movies = []
      JSON.parse(@user.bookmarks||"[]").each do |book|
        info = Faraday.get "https://api.themoviedb.org/3/movie/"+book.to_s+"?language="+cookies[:lang]+"&api_key="+@@api_key
        @movies << JSON.parse(info.body)
      end
      render :books
    else
      redirect_to login_path
    end
  end

  private

  def fetch_movies_by_genre(genre, page)

    genreIds = Faraday.get "https://api.themoviedb.org/3/genre/movie/list?language="+cookies[:lang]+"&api_key="+@@api_key

    genres_hash = JSON.parse(genreIds.body)["genres"]

    genre_ids = genre.map do |g|
      genre_pos = genres_hash.find { |gh| gh["name"] == g }
      genre_pos ? genre_pos["id"] : nil
    end.compact.join(",")

    response = Faraday.get "https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language="+cookies[:lang]+"&page="+page.to_s+"&sort_by=popularity.desc&with_genres="+genre_ids+"&api_key="+@@api_key

    if response.status == 200
      return JSON.parse(response.body)["results"]
    else
      return []
    end

  end

end

CineCue/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def signup
    @user = User.new
  end

  def signup_form
    pass_match = params[:user] ? (params[:user][:password] == params[:user][:password_confirmation]) : (params[:password] == params[:password_confirmation])
    if pass_match
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :signup
      end
    else
      flash[:alert] = "Passwords do not match!"
      render :signup
    end
  end

  def login
  end

  def login_form
    user = User.find_by(username: params[:username])
    if user.present? && user.check?(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = "Invalid Username and/or password!"
      render :login
    end
  end

  def edit_pass
    if @user
      render :edit_pass
    else
      redirect_to login_path
    end
  end

  def edit_pass_form
    if @user
      if params[:password] == params[:password_confirmation]
        if @user.update(password_params)
          redirect_to root_path
        else
          flash[:alert] = "Could not save new password!"
          render :edit_pass
        end
      else
        flash[:alert] = "Passwords do not match!"
        render :edit_pass
      end
    else
      redirect_to login_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  def edit_lang_form
    if @user
      if @user.update(lang_params)
        redirect_to request.referer || root_path
      else
        flash[:alert] = "Could not save new language!"
        render :edit_pass
      end
    else
      cookies[:lang] = lang_params()[:lang]
      redirect_to request.referer || root_path
    end
  end

  private

  def user_params
    params[:user]? (params.require(:user).permit(:username, :email, :password, :lang)) : (params.permit(:username, :email, :password, :lang))
  end

  def password_params
    params.permit(:password)
  end

  def lang_params
    params.permit(:lang)
  end

end

CineCue/app/helpers/application_helper.rb
module ApplicationHelper
end

CineCue/app/helpers/movies_helper.rb
module MoviesHelper
end

CineCue/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CineCue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'icon-sm.svg' %>
  </head>
  <body dir="<% if %w(ar ur).include?(cookies[:lang]) %>rtl<% else %>ltr<% end %>">
    <div class="header">
      <div class="header-logo">
        <a href="/">
          <%= image_tag("icon.svg", alt: "CineCue", class: "logo-image") %>
        </a>
      </div>
      <div class="header-links" dir="<% if %w(ar ur).include?(cookies[:lang]) %>rtl<% else %>ltr<% end %>">
        <% if session[:user_id] %>
          <div class="header-link-card">
            <a href="/books" class="header-link" data-method="delete"><%= @translations["books"] %></a>
            <span class="header-link-underline"></span>
          </div>
          <div class="header-link-card">
            <a href="/pass" class="header-link" data-method="delete"><%= @translations["pass"] %></a>
            <span class="header-link-underline"></span>
          </div>
          <div class="header-link-card">
            <a href="/logout" class="header-link" data-method="delete"><%= @translations["logout"] %></a>
            <span class="header-link-underline"></span>
          </div>
        <% else %>
          <div class="header-link-card">
            <a href="/login" class="header-link" data-method="delete"><%= @translations["login"] %></a>
            <span class="header-link-underline"></span>
          </div>
          <div class="header-link-card">
            <a href="/signup" class="header-link" data-method="delete"><%= @translations["signup"] %></a>
            <span class="header-link-underline"></span>
          </div>
        <% end %>
      </div>
    </div>
    <span class="header-space"></span>
    <div class="main">
      <% genres = @translations["genre"].split(',') %>
      <% signup_page = @translations["signup_page"].split(',') %>
      <div class="lang-div">
        <h2 class="title">󰗊  <%= @translations["change_lang"] %></h2>
        <%= form_with url: lang_path, method: :patch, data: { turbo: false } do |form| %>
          <%= form.label :lang, signup_page[2] %>:
          <%= form.select :lang,
            [
              ['English', 'en'],
              ['Spanish', 'es'],
              ['French', 'fr'],
              ['Hindi', 'hi'],
              ['Urdu', 'ur'],
              ['Turkish', 'tr'],
              ['Arabic', 'ar']
            ],
            { selected: 'en' }, class: "lang-sel" %>&nbsp;<%= form.submit @translations["set_lang"], class: "get-btn" %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

CineCue/app/views/movies/books.html.erb
<h1>󰸕 <%= @translations["books"] %></h1>

<div class="movies-cont">
  <% if @movies.any? %>
    <div class="movies">
      <% @movies.each do |movie| %>
        <div class="movie">
          <strong class="mov-title"> &nbsp;<%= movie['title'] %></strong> (<%= movie['vote_average'].round(1) %>/10)
          <% if @user %><%= button_to @translations["unbookmark"], unbook_path(movie['id']), method: :post, remote: true, class: 'bookmark-btn' %><% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p><%= @translations["no_books"] %></p>
  <% end %>
</div>

CineCue/app/views/movies/index.html.erb
<% genres = @translations["genre"].split(',') %>
<% signup_page = @translations["signup_page"].split(',') %>

<div class="center-n">
  <h1>󰿏 <%= @translations["findmov"] %><% if @user %>, @<%= @user.username %><% end %>.</h1>
  <div class="searchbar">
    <%= form_with url: root_path, method: :get do |form| %>
      <%= label_tag :genre, @translations["sel_genre"] %><br>
      <div class="searchdiv">
        <%= select_tag :genre, options_for_select([
          [genres[0], "Action"],
          [genres[1], "Adventure"],
          [genres[2], "Animation"],
          [genres[3], "Comedy"],
          [genres[4], "Crime"],
          [genres[5], "Documentary"],
          [genres[6], "Drama"],
          [genres[7], "Family"],
          [genres[8], "Fantasy"],
          [genres[9], "History"],
          [genres[10], "Horror"],
          [genres[11], "Music"],
          [genres[12], "Mystery"],
          [genres[13], "Romance"],
          [genres[14], "Science Fiction"],
          [genres[15], "TV Movie"],
          [genres[16], "Thriller"],
          [genres[17], "War"],
          [genres[18], "Western"]
        ]), multiple: true, required: true, class: "gen-sel" %>
        <div class="xbtn">
          <%= submit_tag @translations["get_sug"], class: "get-btn get-xbtn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<h2><%= @translations["mov_sug"] %></h2>
<div class="movies-cont">
  <% if @movies.any? %>
    <div class="movies">
      <% @movies.each do |movie| %>
        <div class="movie">
          <strong class="mov-title"><%= movie['title'] %></strong> (<%= movie['vote_average'].round(1) %>/10)
          <% if @user %><%= button_to @translations["bookmark"], book_path(movie['id']), method: :post, remote: true, class: 'bookmark-btn' %><% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <%= @translations["no_mov"] %>
  <% end %>
  <% if @movies2.any? %>
    <div class="movies">
      <% @movies2.each do |movie| %>
        <div class="movie">
          <strong class="mov-title"><%= movie['title'] %></strong> (<%= movie['vote_average'].round(1) %>/10)
          <% if @user %><%= button_to @translations["bookmark"], book_path(movie['id']), method: :post, remote: true, class: 'bookmark-btn' %><% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>